### ISSUE TITLE
2.23 Crashes at updating games list

### ISSUE THREAD

**Issue by gimmer** [VRPirates/rookie#21] opened 2023-10-01 15:01 UTC
I did an auto update from 2,22. When you hit "updating games list" the game freezes. Downgraded back to 2.22 restored functionality.

If you need any specific logs, let me know

**Comment by akshaybharwani** [comment] 2023-10-31 07:32
> Try launching Rookie with your headset connected, getting it to freeze again, once it does, look inside your headset and you should see a prompt you need to accept.
> 
> Accept it, then relaunch Rookie and it should work.

This worked. And just to note, "Allow Debugging" didn't work for me as it will keep asking this again and again. Choose "Always allow for this PC" instead. 

Maybe this should be included in these steps here: https://wiki.vrpirates.club/Howto/Rookie-Sideloader

**Comment by Chax1** [comment] 2023-10-31 07:34
I'll add it to the page as its currently a bug im still looking into fixing, I sadly cannot reproduce it so itll take some time lol.

**Comment by Chax1** [comment] 2023-11-04 10:28
This should've been fixed with the release of 2.25

**Closed by Chax1** 2023-11-04 10:28 UTC
Labels: bug
