### ISSUE TITLE
Copying the complete list to the clipboard (using CTRL+L/ALT+L) doesn't copy every name

### ISSUE THREAD

**Issue by OldWarez** [VRPirates/rookie#110] opened 2024-05-28 03:11 UTC
The ones I've noticed are Game Names:

Myst
Pong
Pool

...they end up being totally absent in either listing method.

**Comment by frxctura** [comment] 2024-06-15 09:36
I'm unable to reproduce this on 2.29.2, the gamelist properly copies
Myst, is an actual game name within the list, so is Pong, and so is Pool.

**Comment by OldWarez** [comment] 2024-06-29 05:38
This still acts this way here, Win 10:

Fresh install of 2.92.2
Nothing selected in file list
Cursor in one of the fields above the file list so that hitting a keyboard key doesn't jump to that letter.
CTRL+L or ALT+L
Paste into Notepad
Resulting list doesn't have the games mentioned, while they exist in the program's selector

If I highlight one of the mentioned games, move the cursor to another field as above, and copy the package name, -that- copies fine

**Comment by frxctura** [comment] 2024-07-16 14:45
I've committed a change at fix/CopyGameList, instead of building a list when loading it, we now copy the items directly, if you're able to build, give it an attempt and see if this solution works for you, from my testing it seems to have included all items properly now.

**Closed** 2024-08-28 19:52 UTC
Labels: bug
