### ISSUE TITLE
Certain files don't stay in RSL folder

### ISSUE THREAD

**Issue by undead9786** [VRPirates/rookie#163] opened 2024-12-10 07:02 UTC
The settings.json and debuglog.txt keeps defaulting to my downloads folder but pre 2.31.x it would stay in the same folder as the exe. I changed the settings.json to my RSL folder and it will still revert back to the downloads folder.

**Comment by frxctura** [comment] 2024-12-11 06:39
Just to check, did you isolate Windows from Mac? As in, does your VM have a C:/ drive?

**Comment by undead9786** [comment] 2024-12-11 19:04
I don't even have the option but here is the weird part. I left the files untouched for 24 hours and kept doing my normal thing and noticed they were no longer being modified so this time I deleted them and relaunched the exe multiple times, rebooted the VM, did some downloads and movements and it's not popping in that location anymore.
Maybe the exe needed time to recognize the new location between the 2 settings.json?

**Comment by frxctura** [comment] 2024-12-14 13:15
It’s possible this was caused by a different environment setup. The settings.json was using AppDomain.CurrentDomain.BaseDirectory instead of Environment.CurrentDirectory, and I’ve fixed that with commit 9a17dd7.

I'll go ahead and close this issue for now since your files appear to have returned to their expected locations, and this seems to be a unique occurrence.

Additionally, you’re using Parallels, which could introduce some side effects as well. Let me know if you encounter any further issues!

**Closed by frxctura** 2024-12-14 13:15 UTC
Labels: question
